_defaults: &defaults
  docker:
    - image: luongbui/debian_stretch_docker:17.05.0-ce
  environment:
    DOCKER_REPO: "luongbui/flutter"
    TAG: "0.4.4-beta"

_restore_docker_cache: &restore_docker_cache
  restore_cache:
      keys: 
        - &docker_cache_key v1-docker-cache-key

_save_docker_image: &save_docker_image
  name: Save Docker image layer cache
  command: |
    mkdir -p /docker-cache
    docker save -o /docker-cache/image.tar $DOCKER_REPO:$TAG

version: 2
jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --tag $DOCKER_REPO:$TAG .
      - run:
          <<: *save_docker_image 
      - save_cache:
          key: *docker_cache_key
          paths:
            - /docker-cache

  build_from_cache:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - *restore_docker_cache
      - run:
          name: Load Docker image layer cache # From: https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
          command: |
            set +o pipefail
            docker load -i /docker-cache/image.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=image --tag $DOCKER_REPO:$TAG .
      - run:
          <<: *save_docker_image  
      - save_cache:
          key: *docker_cache_key
          paths:
            - /docker-cache

  upload_hub:
    <<: *defaults
    steps:
      - *restore_docker_cache
      - setup_remote_docker
      - run:
          name: Upload Docker image to Hub
          command: |
            docker load < /docker-cache/image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_REPO:$TAG

workflows:  
  version: 2

  build_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - build_from_cache:
          filters:
            branches:
              only:
                - master             
      - upload_hub:
          filters:
            branches:
              only:
                - master
          requires:
            - build_from_cache

