_defaults: &defaults
  docker:
    - image: luongbui/debian_stretch_docker:17.05.0-ce
  environment:
    DOCKER_REPO: "luongbui/flutter"
    TAG: "0.4.4-beta"

version: 2
jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --tag $DOCKER_REPO:$TAG .
            mkdir -p /docker-cache
            docker save -o /docker-cache/image.tar $DOCKER_REPO:$TAG
      - persist_to_workspace:
          root: /docker-cache
          paths:
            - image.tar

  upload_hub:
    <<: *defaults
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /docker-cache
      - run:
          name: Upload Docker image to Hub
          command: |
            docker load < /docker-cache/image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_REPO:$TAG

workflows:  
  version: 2

  build_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master             
      - upload_hub:
          filters:
            branches:
              only:
                - master
          requires:
            - build

